version: '3'

services:
  tendermint_abci:
    build: ./app
    image: tendermint_abci
    container_name: tendermint_abci
    restart: always
    ports:
      - 26658:26658
    depends_on:
      - db


  tendermint_init:
    image: tendermint/tendermint:v0.32.8
    container_name: tendermint_init
    command: "init"
    volumes:
      - ./tendermint/data:/tendermint

  tendermint_core:
    image: tendermint/tendermint:v0.32.8
    container_name: tendermint_core
    depends_on:
      - tendermint_init
      - tendermint_abci
    restart: always
    command: "node"
    volumes:
      - ./tendermint/data:/tendermint
    ports:
      - 26656:26656
      - 26657:26657


  db:
    image: mariadb:10.5.4
    restart: always
    volumes:
      - ./storage/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_PASSWORD: my_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
    ports:
      - 3306:3306

